cakeproject/cakeproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # Mounting Routes
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

cakeproject/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('cakes/', views.cakes_index, name='index'),
    # path('cakes/<int:cake_id>', views.cakes_detail, name='detail'),
    path('cakes/<int:pk>', views.CakeDetail.as_view(), name='detail'),
    path('cakes/create', views.CakeCreate.as_view(), name='cakes_create'),
    path('cakes/<int:pk>/update', views.CakeUpdate.as_view(), name='cakes_update'),
    path('cakes/<int:pk>/delete', views.CakeDelete.as_view(), name='cakes_delete'),

    # Recipe
    # path('recipes/', views.RecipeList.as_view(), name='recipe_index'),
    # path('recipes/<int:pk>/', views.RecipeDetail.as_view(), name='recipe_detail'),
    # path('cakes/<int:cake_id>/add_recipe', views.RecipeCreate.as_view(), name='add_recipe'),
    path('cakes/<int:pk>/add_recipe', views.add_recipe, name='add_recipe'),
    path('recipes/<int:pk>/update', views.RecipeUpdate.as_view(), name='recipes_update'),
    path('recipes/<int:pk>/delete/', views.RecipeDelete.as_view(), name='recipes_delete'),

    # Authentication Paths
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
]

cakeproject/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

FLAVOURS = (
    ('#f4f0d2', 'Plain Sponge'),
    ('#e8b26b', 'Caramel'),
    ('#d4a373', 'Chocolate'),
    ('#fff3c9', 'Cream Cheese'),
    ('#fad2e6', 'Fruit'),
    ('#d48c55', 'Spiced'),
    ('#fffeeb', 'Vanilla'),
    ('#f1b0ff', 'Experimental')
)
# Create your models here.

class Cake(models.Model):
    name = models.CharField(max_length=100)
    flavours = models.CharField(max_length=7, choices=FLAVOURS, default=FLAVOURS[0][0])
    description = models.TextField(max_length=250)
    imageurl = models.CharField(default=None, blank=True, max_length=300, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('detail', kwargs = {'pk': self.id})

    def __str__(self):
        return f"{self.name}"

class Recipe(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250, null=True)
    ingredients = models.TextField(max_length=500)
    instructions = models.TextField(max_length=500)
    imageurl = models.CharField(default=None, blank=True, max_length=300, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    cake = models.ForeignKey(Cake, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title} added to cake #{self.cake} by user #{self.created_by}"

    class Meta:
        ordering = ['created_date']
    
    def get_absolute_url(self):
        return reverse('detail', kwargs = {'pk': self.cake_id})

cakeproject/main_app/forms.py
from django.forms import ModelForm
from .models import Recipe
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, PasswordResetForm
from django.contrib.auth.models import User

class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'description', 'ingredients', 'instructions', 'imageurl']
        success_message = "Recipe successfully created."


# Custom Form for Sign-up - extending the UserCreationForm to include email address as a field:

class NewUserForm(UserCreationForm):
  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2']
  
  def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
          user.save()
        return user

cakeproject/main_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from .models import Cake, Recipe
from .forms import NewUserForm, RecipeForm
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormMixin
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.list import MultipleObjectMixin
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, PasswordResetForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView, LoginView, LogoutView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator

# Create your views here.

# Cake CRUD operations

class CakeDetail(DetailView):
    model = Cake
    def get_context_data(self, **kwargs):
        # Defines the context as the CakeDetail view being accessed
        context = super(CakeDetail, self).get_context_data(**kwargs)
        # Fetches the currently-accessed page of paginated objects
        page = self.request.GET.get('page')
        # Initializes the paginator, sets the paginated objects to a list of Recipes attributed to the currently-accessed Cake, 
        # orders the filtered list by the date of creation, and asserts 3 Recipes per page
        paginator = Paginator(Recipe.objects.filter(cake=self.get_object()).order_by('created_date'), 3)
        # declares that any use of "page_obj" in the relevant template is equated to the current page of Recipes
        context['page_obj'] = paginator.get_page(page)
        # declares that any use of 'form' in the relevant template is equated to the RecipeForm CBV
        context['form'] = RecipeForm
        return context


class CakeCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Cake
    fields = ['name', 'flavours', 'description', 'imageurl']
    success_message = "Cake successfully created."
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class CakeUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Cake
    fields = ['name', 'flavours', 'description', 'imageurl']
    success_message = "Cake successfully updated."
    
class CakeDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Cake
    success_message = "Cake successfully deleted."
    success_url = '/cakes/'


# Home/Landing page

def home(request):
    return render(request, 'home.html')

def cakes_index(request):
    # cakes = all established Cake objects in the DB
    cakes = Cake.objects.all()
    # initializes the paginator and asserts that there must be 3 cakes to a page
    paginator = Paginator(cakes, 4)
    # defines the page number of the currently accessed page of cakes
    page_number = request.GET.get('page')
    # defines the contents of the currently accessed page of cakes
    page_obj = paginator.get_page(page_number)
    # renders the cakes index and passes the page_obj variable to any use of 'page_obj' in the template
    return render(request, 'cakes/index.html', {'page_obj': page_obj})

# def cakes_detail(request, pk):
#     cake = Cake.objects.get(id=pk)
#     recipe_form = RecipeForm
#     return render(request, "cakes/detail.html", {'cake': cake, 'recipe_form': recipe_form})

#adding RECIPE CRUD OPERATIONS - RecipeUpdate view, Richard 28/6/22
class RecipeUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Recipe
    fields = ['title', 'description', 'ingredients', 'instructions', 'imageurl']
    success_message = "Recipe Successfully Updated."
    


#Richard uncommented this class 28/6/22
# class RecipeCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
#     model = Recipe
#     fields = ['title', 'description', 'ingredients', 'instructions', 'imageurl']
#     success_message = "Recipe successfully created."
#     def form_valid(self, form):
#         form.instance.created_by = self.request.user
#         form.instance.cake = self.request.cake_id
#         return super().form_valid(form)

"""@login_required
def add_feeding(request, cat_id):
    # where req.body in express represented the posted form data, django uses request.POST
    form = FeedingForm(request.POST)
    print(form)
    if form.is_valid():
        # Collect the data, but do not commit it to the DB
        new_feeding = form.save(commit=False)
        # sets the cat_id value of cat_id passed from the form(?)
        new_feeding.cat_id = cat_id
        # save to db
        new_feeding.save()
        return redirect('detail', cat_id = cat_id)"""

@login_required
def add_recipe(request, pk):
    form = RecipeForm(request.POST)
    print(form)
    if form.is_valid():
        new_recipe = form.save(commit = False)
        new_recipe.cake_id = pk
        form.instance.created_by = request.user
        new_recipe.save()
        messages.success(request, f"Recipe successfully added.")
        return redirect('detail', pk = pk)

class RecipeDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Recipe
    success_message = "Recipe successfully deleted."
    #success_url = reverse_lazy('detail', kwargs = {'pk': model.cake_id})
    def get_success_url(self):
        return reverse('detail', kwargs={'pk' : self.object.cake_id})
    

# Authentication Views

# Signup View - using new custom form in forms.py called NewUserForm to allow for email input on signup
def signup(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'You successfully signed up and are now logged in.')
            return redirect('/')
        else:
            messages.error(request, "Invalid sign up - try again.")
    
    form = NewUserForm()
    return render(request, 'registration/signup.html', {'form': form})


# Password Change - specifying success url redirect, otherwise will default to a URL with the name 'password_change_done' which will need a new view & template specified.
class PasswordChange(SuccessMessageMixin, PasswordChangeView):
    success_message = "Password changed successfully."
    success_url = '/'

class LoginView(SuccessMessageMixin, LoginView):
    def form_valid(self, form):
            messages.success(self.request, f"You have successfully logged in!")
            return super().form_valid(form)

class LogoutView(LoginRequiredMixin, SuccessMessageMixin, LogoutView):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.info(request, "You have successfully logged out.")
        return super().dispatch(request, *args, **kwargs)

cakeproject/main_app/templates/main_app/cake_confirm_delete.html
{% extends 'base.html' %}
{% load bulma_tags %}

{% block title %}
Delete Cake
{% endblock %}

{% block content %}

<section class="section section--form">
  <div class="container">
    <div class="content box">
      <h1>Delete {{ cake.name }}</h1>

      <h4>Are you sure you want to delete <span class="red-text">{{ cake.name }}</span>?</h4>

      <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="button is-primary">
        <br>
        <br>
        <p><a href="{% url 'detail' cake.id %}">Cancel</a></p>
    </form> 
    </div>
    
  </div>

</section>

  
{% endblock %}

cakeproject/main_app/templates/main_app/cake_detail.html
{% extends 'base.html' %}

{% block title %}
{{ cake.name }}
{% endblock %}

{% block content %}

<h2>{{cake.name}} Details</h2>
<p>Primary Flavour: {{cake.get_flavours_display}} </p>
<p>Description: {{cake.description}} </p>
<hr>
<p>Added by: {{cake.created_by}}</p>
<br>
<hr>
<br>

{% if user.id == cake.created_by.id %}
<a href="{% url 'cakes_update' cake.id %}">Edit Cake</a>
<a href="{% url 'cakes_delete' cake.id %}">Delete Cake</a>
{% endif %}

{% if user.is_authenticated %}
<!-- <a href ="{% url 'add_recipe' cake.id %}">Add A Recipe</a> -->
<a id="modal-button" class="btn recipe">Add your own recipe for {{cake.name}}</a>

<div id="recipe-form" class="modal">
    <div class="modal-content">
        <h4>New Recipe</h4><span class="close">&times;</span>
        <form action="{% url 'add_recipe' cake.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add Recipe" class="btn">
        </form>
    </div>
</div>
    

{% endif %}
<br>
<hr>
<br>
<h3>Recipes for {{ cake.name }}</h3>


{% if cake.recipe_set.all %}

    {% for recipe in page_obj %}
        <div class="card">
            <div class="card-content">
                <h4>
                    {{ recipe.title }}
                </h4>
                <p><strong>Description: </strong>{{ recipe.description}}</p>
                <p>Added by {{ recipe.created_by }} on {{ recipe.created_date }}.</p>
            </div>
            {% if user.id == recipe.created_by.id %}
            <div class="card-action">
                <a href="{% url 'recipes_update' recipe.id %}">Edit</a>
                <a href="{% url 'recipes_delete' recipe.id %}">Delete</a>
            </div>
            {% endif %}
        </div>
    {% endfor %}
    
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                ||
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% else %}
                &laquo; first
                ||
                previous
            {% endif %}
    
            <span class="current">
                || Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} ||
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                ||
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% else %}
                next
                ||
                last &raquo;
            {% endif %}
        </span>
    </div>

{% else %}
    <p>No recipes yet</p>
{% endif %}


{% endblock %}

cakeproject/main_app/templates/main_app/cake_form.html
{% extends 'base.html' %}
{% load bulma_tags %}

{% block title %}
    {% if object  %}
        Edit {{object.name}}
    {% else %}
        Add New Cake
    {% endif %}
{% endblock %}

{% block content %}

<section class="section section--form">
    <div class="container is-max-desktop">
        <div class="content box">
            {% if object %}
                <h1>Edit {{object.name}}</h1>
            {% else %}
                <h1>Add a Cake</h1>
            {% endif %}

            <form action ="" method="post">
                
                {% csrf_token %}
                {{ form|bulma }}
        
                <input type="submit" value="Submit" class="button is-primary">
            </form>
        </div>    
    </div>
</section>


{% endblock %}

cakeproject/main_app/templates/main_app/recipe_confirm_delete.html
{% extends 'base.html' %}
{% load bulma_tags %}

{% block title %}
Delete Recipe
{% endblock %}

{% block content %}

<section class="section section--form">
  <div class="container">
    <div class="content box">
      <h1>Delete</h1>

      <h4>Are you sure you want to delete <span class="red-text">{{ recipe.title }}</span>?</h4>

      <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="button is-primary">
        <p><a href="{% url 'detail' recipe.cake_id %}">Cancel</a></p>
      </form>
    </div>
    
  </div>

</section>

{% endblock %}

cakeproject/main_app/templates/main_app/recipe_detail.html
{% extends 'base.html' %}

{% block title %}
{{ recipe.name }}
{% endblock %}

{% block content %}
<title> Recipe Details</title>
<h2>{{recipe.name}} Details</h2>

<p>Description: {{recipe.description}} </p>
<hr>
<p>Added by: {{recipe.created_by}}</p>
<br>
<hr>
<br>

{% if user.id == cake.created_by.id %}
<a href="{% url 'recipes_update' cake.id %}">Edit Cake</a>
<a href="{% url 'recipes_delete' cake.id %}">Delete Cake</a>
{% endif %}

{% if user.is_authenticated %}
<!-- <a href ="{% url 'add_recipe' cake.id %}">Add A Recipe</a> -->
<a id="modal-button" class="btn recipe">Add your own recipe for {{cake.name}}</a>

<div id="recipe-form" class="modal">
    <div class="modal-content">
        <h4>New Recipe</h4><span class="close">&times;</span>
        <form action="{% url 'add_recipe' cake.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add Recipe" class="btn">
        </form>
    </div>
</div>
    

{% endif %}
<br>
<hr>
<br>
<h3>Recipes for {{ cake.name }}</h3>


{% if cake.recipe_set.all %}

    {% for recipe in cake.recipe_set.all %}
        <div class="card">
            <div class="card-content">
                <h4>
                    {{ recipe.title }}
                </h4>
                <p><strong>Description: </strong>{{ recipe.description}}</p>
                <p>Added by {{ recipe.created_by }} on {{ recipe.created_date }}.</p>
            </div>
            {% if user.id == recipe.created_by.id %}
            <div class="card-action">
                <a href="#">Edit</a>
                <a href="#">Delete</a>
            </div>
            {% endif %}
        </div>
    {% endfor %}

{% else %}
    <p>No recipes yet</p>
{% endif %}


{% endblock %}

cakeproject/main_app/templates/main_app/recipe_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Add A Recipe</h1>
{% endif %}

    <form action ="" method="post">
        {% csrf_token %}

        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="submit" class="btn">
    </form>

{% endblock %}